language: node_js
node_js:
- '4'
env:
  global:
    secure: orU+oZpgaGeR1IDirCe87msd2HemNCLS+8WgcHccPxLZcc81ZACoTAUg3kA+en0xrJQ6Dm/GP3OOv2Xj30dl7ufzm6dcr0ivgkcq+p0eq38qiO0ZKlW6GwcAU1hfirU7HfRbWipIDyclzDOV5LdLFZ1C6/9BmoBb/Dbjb4dlXURW3SJ+Wl/wFqcIRpZ8gHnXDt80uBF3i+fXi4sh3QRtbUE4iIPlMVPJiOvW6poS2OF0U5fJ9DawE9fIC6jmFzfXSyaU5PLdoZWYuPnlSKQsuOGL419RW8DcmDJnf86i90BCVg1L5lIzNmPS1xYFaJoZbMY1fFeUFJ+i/nlZ+nTRW7G638C4BU7NCtgo5PzN6KbTSimLLe+0xpBRiejGllYcoARRn3PKKeyll29o65PQC690IR8hXchY725kik24RAKkfWRLhfcoV01q7NsweUW8zFvwjmZsXPvvdEDAVTYwJVw1aREMetiCzgsWFDzwEUT5D9f7I83+rfpKEzoVqgCeGUbnl2sbplwIg70pGSKq+gLHxppe5M/tLHQs37JLWML6AXt7YAXy32sNGQF4cMGF7z1Aj6Svfq3rOeZdWADl+HvQYi2GY+BbQiTpeBqobybYLcnonKccgqN4L8WAWKX35jqTcgbQx5wablkQFerzK1thg9/DkNZXHpnERr4QwrY=
before_script:
- npm install -g concurrently
script:
- npm run build_prod
- karma start --single-run

before_deploy: "tar -zcvf surveyeditor.tar.gz package"
deploy:
- provider: releases
  api_key:
    secure: Fe+bRA8WO1T345iLvXkrOusCkr9RTblojIGfTNV80sY9+Q5Zt7gPeDa2snvlvTWmdkN+y2vZzP73JN7HZv1kxg1egt9lFHvllGw6YTeka+CE74sPnHGMFx4OqJHtd4D0hLVXg5wM8BbgFJ4R+jqbLwWY2+brDY1hsM7bXSf17kjcUFhKCoyYMvHCr5cngf99igTaFDYFc3IcNMyfXgqsMiFR415v0CklfZiEQU4Tt2Eu8foC27hApzpSQVgLtIAsYPVVTFYD9yghRcpth5ouL5KTq83Qa/E7senwTJKHU1wBeOT/6BNwKxlXQrBzjAKTmNrB1KG0ES3UR5TuXocIid1+cEK1jUpwl7gldKYSdckTMTM1FDTZ7Wj2hrIof2NyPKIaiCk7c4Qlc61XR5zQCZF4n3Yyxtj9FLRkv+9DQpfKOS5yEqlAXqdU4s5kv3SN3FXMMDBNGv4szI1xMGKT+ld8rT2FnHJcrhn9QYlyCv/gahb3igOOC+1LRmo6oGHg3/ks8EeTOwMR/pOY0BuK6RxVoD2Da4ZD7pY9+/CthF9+1bcHaHeeQYWTs47NZijX/zawl/Xc65ktGCzav2hX9M0jWBckDiGRsB/34MuFvPGtuIFhJAxsb0PGO3bEEcMzMpdte9TxO0zlufoHRHpfifehbNKkmL2582fUiYS1ouI=
  file: surveyeditor.tar.gz
  skip_cleanup: true
  on:
    tags: true
- provider: script
  script: chmod +x ./deploy_npm.sh && ./deploy_npm.sh
  skip_cleanup: true
  on:
    tags: true